/**
 * CampusMart - Complete 150+ Unique Product Dataset
 * Structured cleanly into 3 main sections: Boys (50+), Girls (50+), Student Essentials (50+)
 */

const CAMPUS_PRODUCTS = [
  // ==========================================
  // BOYS SECTION (50 UNIQUE PRODUCTS: B101 - B150)
  // ==========================================
  {
    id: "B101",
    name: "Campus Trend Heavyweight Oversized Graphic Tee",
    section: "boys",
    category: "Fashion",
    price: 699,
    originalPrice: 1299,
    discount: 46,
    rating: 4.8,
    reviews: 245,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
    description: "240 GSM 100% combed cotton streetwear oversized tee for maximum campus comfort and style.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B102",
    name: "Vintage Wash Denim Jacket with Fleece Collar",
    section: "boys",
    category: "Fashion",
    price: 1899,
    originalPrice: 3499,
    discount: 45,
    rating: 4.9,
    reviews: 188,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80",
    description: "Classic rugged denim jacket with warm fleece lining. Perfect for early morning lectures and evening hangouts.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B103",
    name: "Urban Cargo Jogger Pants with 6 Pockets",
    section: "boys",
    category: "Fashion",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.7,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80",
    description: "Stretchable twill cotton multi-pocket cargo pants built for durability and everyday campus utility.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B104",
    name: "Apex White Chunky Campus Sneakers",
    section: "boys",
    category: "Shoes",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.8,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80",
    description: "Breathable mesh upper with cushioned memory foam sole for all-day campus walking.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B105",
    name: "Pro-Series Waterproof Gym & Travel Duffle",
    section: "boys",
    category: "Bags",
    price: 849,
    originalPrice: 1699,
    discount: 50,
    rating: 4.6,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "Spacious duffle bag with dedicated shoe compartment and wet pocket. Ideal for gym and weekend hostel trips.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B106",
    name: "Minimalist Matte Black Chronograph Watch",
    section: "boys",
    category: "Watches",
    price: 1199,
    originalPrice: 2499,
    discount: 52,
    rating: 4.7,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    description: "Stainless steel quartz movement watch with scratch-resistant glass and water resistance up to 30m.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B107",
    name: "Philips Cordless Waterproof Beard Trimmer",
    section: "boys",
    category: "Gadgets",
    price: 899,
    originalPrice: 1495,
    discount: 40,
    rating: 4.8,
    reviews: 810,
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=600&q=80",
    description: "Self-sharpening stainless steel blades with 60-min cordless runtime for hostel grooming.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B108",
    name: "UrbanGabru Zero Gravity Hair Styling Wax",
    section: "boys",
    category: "Accessories",
    price: 299,
    originalPrice: 450,
    discount: 33,
    rating: 4.5,
    reviews: 512,
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    description: "Strong hold matte finish hair wax enriched with natural earth clay and almond oil.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B109",
    name: "Fogg Intense Body Deodorant Spray (150ml Pack of 2)",
    section: "boys",
    category: "Accessories",
    price: 399,
    originalPrice: 650,
    discount: 38,
    rating: 4.7,
    reviews: 630,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "Long-lasting no-gas fragrance spray engineered for active campus sports and everyday fresh wear.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B110",
    name: "Tactical Canvas Belt with Quick-Release Metal Buckle",
    section: "boys",
    category: "Accessories",
    price: 349,
    originalPrice: 799,
    discount: 56,
    rating: 4.6,
    reviews: 195,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80",
    description: "Heavy-duty nylon webbing belt with solid alloy buckle for jeans and cargo trousers.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B111",
    name: "Cozy Fleece Pullover Campus Hoodie",
    section: "boys",
    category: "Fashion",
    price: 1149,
    originalPrice: 2299,
    discount: 50,
    rating: 4.8,
    reviews: 375,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80",
    description: "Warm brush-back fleece hoodie with kangaroo pocket and adjustable drawstring hood.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B112",
    name: "Classic High-Top Canvas Sneakers",
    section: "boys",
    category: "Shoes",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.7,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
    description: "Timeless rubber toe cap high-top sneakers matching any casual college outfit.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B113",
    name: "Anti-RFID Genuine Leather Bi-Fold Wallet",
    section: "boys",
    category: "Accessories",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 440,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80",
    description: "Handcrafted full-grain leather wallet with 8 card slots, coin pocket, and RFID blocking protection.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B114",
    name: "Polarized Retro Square Sunglasses",
    section: "boys",
    category: "Accessories",
    price: 599,
    originalPrice: 1299,
    discount: 54,
    rating: 4.6,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
    description: "UV400 protection glare-free polarized sunglasses for sunny campus strolls.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B115",
    name: "Slim Fit Solid Casual Cotton Shirt",
    section: "boys",
    category: "Fashion",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.5,
    reviews: 260,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
    description: "100% breathable poplin cotton shirt suitable for presentations and everyday wear.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B116",
    name: "BoAt Airdopes True Wireless Bluetooth Earbuds",
    section: "boys",
    category: "Gadgets",
    price: 1299,
    originalPrice: 2990,
    discount: 57,
    rating: 4.7,
    reviews: 950,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
    description: "42 hours playback time, quad mics with ENx noise cancellation and ENx low-latency gaming mode.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B117",
    name: "Multi-Pocket Messenger Crossbody Bag",
    section: "boys",
    category: "Bags",
    price: 749,
    originalPrice: 1499,
    discount: 50,
    rating: 4.6,
    reviews: 135,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
    description: "Compact canvas sling bag for tablet, notebook, charger, wallet and phone.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B118",
    name: "Rugged Stainless Steel Digital Sports Watch",
    section: "boys",
    category: "Watches",
    price: 799,
    originalPrice: 1699,
    discount: 53,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80",
    description: "Shockproof 50m water resistant digital watch with LED backlight, stopwatch and alarm.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B119",
    name: "Lightweight Breathable Mesh Running Shoes",
    section: "boys",
    category: "Shoes",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.6,
    reviews: 295,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    description: "Flexible sole with extra arch support for sports ground and hostel workout sessions.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B120",
    name: "Relaxed Fit Distressed Denim Jeans",
    section: "boys",
    category: "Fashion",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.7,
    reviews: 190,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
    description: "Medium wash cotton denim with subtle distressing for effortless street style.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B121",
    name: "Classic Polo Neck Cotton T-Shirt",
    section: "boys",
    category: "Fashion",
    price: 549,
    originalPrice: 1099,
    discount: 50,
    rating: 4.5,
    reviews: 165,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80",
    description: "Ribbed collar Pique cotton polo shirt for lab days and casual presentations.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B122",
    name: "Full HD Action Camera with Waterproof Case",
    section: "boys",
    category: "Gadgets",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.6,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
    description: "1080p 60fps wide angle camera with mounting accessories for bike trips & campus vlogging.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B123",
    name: "Fastrack Smart Fitness Band with SpO2",
    section: "boys",
    category: "Gadgets",
    price: 1599,
    originalPrice: 2995,
    discount: 46,
    rating: 4.7,
    reviews: 480,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80",
    description: "1.3-inch OLED touch display, heart rate monitor, sleep tracking and 10-day battery life.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B124",
    name: "Classic Brown Leather Loafers",
    section: "boys",
    category: "Shoes",
    price: 1699,
    originalPrice: 3299,
    discount: 48,
    rating: 4.8,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=600&q=80",
    description: "Synthetic leather slip-on loafers perfect for formal college functions & interviews.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B125",
    name: "Padded Waterproof Laptop Sleeve (15.6 Inch)",
    section: "boys",
    category: "Bags",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.7,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
    description: "Shockproof neoprene padding with front accessory pocket for charger & mouse.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B126",
    name: "Heavy-Duty Gym Wrist Support Wraps",
    section: "boys",
    category: "Accessories",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.6,
    reviews: 215,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
    description: "Elastic thumb loop wrist straps for heavy bench press and workout safety.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B127",
    name: "Solid College Tracksuit Set (Jacket + Joggers)",
    section: "boys",
    category: "Fashion",
    price: 1799,
    originalPrice: 3599,
    discount: 50,
    rating: 4.8,
    reviews: 185,
    image: "https://images.unsplash.com/photo-1483721077596-37452505ee0d?auto=format&fit=crop&w=600&q=80",
    description: "Poly-cotton breathable tracksuit set for winter mornings and athletic practice.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B128",
    name: "Wild Stone Code Copper Perfume (120ml)",
    section: "boys",
    category: "Accessories",
    price: 449,
    originalPrice: 750,
    discount: 40,
    rating: 4.7,
    reviews: 510,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=600&q=80",
    description: "Intense woody citrus fragrance designed for active daytime campus confidence.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B129",
    name: "Aviator Metal Frame Sunglasses",
    section: "boys",
    category: "Accessories",
    price: 499,
    originalPrice: 1199,
    discount: 58,
    rating: 4.5,
    reviews: 130,
    image: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=600&q=80",
    description: "Classic gold frame teardrop aviators with UV400 green tinted lenses.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B130",
    name: "Beardo Charcoal Deep Clean Face Wash",
    section: "boys",
    category: "Accessories",
    price: 220,
    originalPrice: 350,
    discount: 37,
    rating: 4.6,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Activated charcoal formula removes campus dust, excess oil and pollution.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B131",
    name: "Checkered Cotton Casual Button Down Shirt",
    section: "boys",
    category: "Fashion",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    description: "Breathable plaid cotton shirt layered effortlessly over plain tees.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B132",
    name: "Comfy Memory Foam Hostel Slides",
    section: "boys",
    category: "Shoes",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.5,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=600&q=80",
    description: "Waterproof EVA cushion sliders for hostel room, washroom & mess walk.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B133",
    name: "Full Metal Analog Leather Strap Watch",
    section: "boys",
    category: "Watches",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.7,
    reviews: 165,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
    description: "Genuine brown leather strap watch with silver dial face.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B134",
    name: "Fast Charging 20000mAh Power Bank with Dual Output",
    section: "boys",
    category: "Gadgets",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.8,
    reviews: 670,
    image: "https://images.unsplash.com/photo-1609592424074-984407b31274?auto=format&fit=crop&w=600&q=80",
    description: "22.5W Power Delivery fast charging power bank for smartphones & tablets.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B135",
    name: "Canvas Utility Crossbody Chest Bag",
    section: "boys",
    category: "Bags",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.6,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "Hands-free chest rig bag with earphone cable port and multiple zip compartments.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B136",
    name: "Pack of 3 Cotton Stretch Boxer Briefs",
    section: "boys",
    category: "Accessories",
    price: 499,
    originalPrice: 899,
    discount: 44,
    rating: 4.7,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    description: "Moisture-wicking combed cotton innerwear with smooth elastic waistband.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B137",
    name: "Heavy Knit Winter Beanie Cap",
    section: "boys",
    category: "Accessories",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.6,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=600&q=80",
    description: "Soft acrylic ribbed skull cap keeping you cozy during late night study sessions.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B138",
    name: "Casual Printed Half Sleeve Hawaiian Shirt",
    section: "boys",
    category: "Fashion",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.5,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80",
    description: "Rayon printed relaxed shirt for college fest, trip and beach days.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B139",
    name: "Leather Formal Oxford Dress Shoes",
    section: "boys",
    category: "Shoes",
    price: 1899,
    originalPrice: 3799,
    discount: 50,
    rating: 4.8,
    reviews: 110,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=600&q=80",
    description: "Polished faux leather lace-up shoes for college convocation and formal events.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B140",
    name: "Compact Stainless Steel Multitool Pocket Knife",
    section: "boys",
    category: "Gadgets",
    price: 449,
    originalPrice: 899,
    discount: 50,
    rating: 4.7,
    reviews: 230,
    image: "https://images.unsplash.com/photo-1588619461328-98e388147d3d?auto=format&fit=crop&w=600&q=80",
    description: "11-in-1 multi tool with bottle opener, scissors, pliers & screwdrivers for hostel room.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B141",
    name: "Slim Fit Chino Trousers",
    section: "boys",
    category: "Fashion",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.6,
    reviews: 175,
    image: "https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=600&q=80",
    description: "Versatile stretch cotton chino pants suitable for casual and semi-formal wear.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B142",
    name: "Black Metal Stainless Steel Cuban Chain Bracelet",
    section: "boys",
    category: "Accessories",
    price: 299,
    originalPrice: 699,
    discount: 57,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1611591475143-be88407470bf?auto=format&fit=crop&w=600&q=80",
    description: "Non-tarnish rustproof 8mm thick curb chain bracelet for guys.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B143",
    name: "Nivea Men Dark Spot Reduction Face Wash",
    section: "boys",
    category: "Accessories",
    price: 199,
    originalPrice: 299,
    discount: 33,
    rating: 4.7,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "10x vitamin C complex formula reducing dullness and sun tan.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "B144",
    name: "Water Resistant Sports Armband Phone Case",
    section: "boys",
    category: "Gadgets",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.5,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80",
    description: "Touchscreen compatible neoprene armband strap for campus running and workout.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "B145",
    name: "Single Breasted Casual College Blazer",
    section: "boys",
    category: "Fashion",
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.8,
    reviews: 95,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    description: "Sleek textured blazer jacket tailored for college placements and formal speeches.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B146",
    name: "Pack of 5 Ankle Length Sports Socks",
    section: "boys",
    category: "Accessories",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.7,
    reviews: 410,
    image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=600&q=80",
    description: "Cushioned heel and toe cotton socks with mesh ventilation.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B147",
    name: "Retro Wooden Grain Frame Sunglasses",
    section: "boys",
    category: "Accessories",
    price: 449,
    originalPrice: 999,
    discount: 55,
    rating: 4.6,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight polycarbonate sunglasses with stylish wood texture arms.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B148",
    name: "Beardo Godfather Beard Oil (30ml)",
    section: "boys",
    category: "Accessories",
    price: 299,
    originalPrice: 450,
    discount: 33,
    rating: 4.6,
    reviews: 340,
    image: "https://images.unsplash.com/photo-1626015366517-293708e330a1?auto=format&fit=crop&w=600&q=80",
    description: "Nourishing almond and argan oil blend for non-greasy beard growth & sheen.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "B149",
    name: "High-Density Foam Yoga & Fitness Mat",
    section: "boys",
    category: "Accessories",
    price: 649,
    originalPrice: 1299,
    discount: 50,
    rating: 4.7,
    reviews: 215,
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=600&q=80",
    description: "6mm anti-skid TPE eco mat with carrying strap for hostel workout.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "B150",
    name: "Casual Slip-On Canvas Loafer Shoes",
    section: "boys",
    category: "Shoes",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.6,
    reviews: 190,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=600&q=80",
    description: "Flexible breathable canvas upper with elastic side gores for easy wearing.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },

  // ==========================================
  // GIRLS SECTION (50 UNIQUE PRODUCTS: G201 - G250)
  // ==========================================
  {
    id: "G201",
    name: "Flowy Floral Print Chiffon Maxi Dress",
    section: "girls",
    category: "Dresses",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.9,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    description: "Soft breathable layered chiffon maxi dress with ruffled waistline. Elegant choice for college fests & outings.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G202",
    name: "Pastel Oversized Graphic Drop-Shoulder Tee",
    section: "girls",
    category: "Tops",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.8,
    reviews: 450,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80",
    description: "Combed 100% bio-wash cotton tee in soothing aesthetic lavender pastel shade.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G203",
    name: "High-Waist Wide-Leg Boyfriend Denim Jeans",
    section: "girls",
    category: "Jeans",
    price: 1299,
    originalPrice: 2599,
    discount: 50,
    rating: 4.8,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
    description: "Trendy 90s style loose fitting high-rise denim with comfortable stretch waist.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G204",
    name: "Chunky Retro Pastel Platform Sneakers",
    section: "girls",
    category: "Shoes",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.9,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight elevated platform sneakers with multi-tone pastel panels.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G205",
    name: "Aesthetic Canvas Tote Bag with Zip & Pocket",
    section: "girls",
    category: "Bags",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
    description: "Heavy canvas cotton shoulder tote spacious enough for iPad, books, water bottle and makeup pouch.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G206",
    name: "Matte Liquid Waterproof Lipstick Pack of 4",
    section: "girls",
    category: "Beauty",
    price: 349,
    originalPrice: 799,
    discount: 56,
    rating: 4.7,
    reviews: 740,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80",
    description: "Non-transfer smudge-proof 16 hour velvet matte liquid lip colors in nude & pink shades.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G207",
    name: "Minimalist Rose Gold Mesh Strap Quartz Watch",
    section: "girls",
    category: "Accessories",
    price: 999,
    originalPrice: 2199,
    discount: 54,
    rating: 4.8,
    reviews: 260,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-thin stainless steel mesh bracelet watch with diamond crystal dial markers.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G208",
    name: "Ceramic Fast Heating Hair Straightener Brush",
    section: "girls",
    category: "Beauty",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "Anti-scald 3D heating teeth brush giving silky smooth salon finish in 3 minutes.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G209",
    name: "Floral Body Mist Fragrance Spray (200ml)",
    section: "girls",
    category: "Beauty",
    price: 399,
    originalPrice: 699,
    discount: 43,
    rating: 4.8,
    reviews: 480,
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=600&q=80",
    description: "Refreshing blend of French lavender and vanilla blossom for day-long floral essence.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G210",
    name: "Cropped Denim Jacket with Distressed Details",
    section: "girls",
    category: "Tops",
    price: 1399,
    originalPrice: 2799,
    discount: 50,
    rating: 4.8,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?auto=format&fit=crop&w=600&q=80",
    description: "Versatile washed blue cropped denim jacket over dresses or high-waisted tops.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G211",
    name: "Cute Mini Quilted Leather Backpack",
    section: "girls",
    category: "Bags",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.7,
    reviews: 350,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
    description: "Compact dual-pocket convertible shoulder mini backpack for college style.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G212",
    name: "Plush Fleece Oversized Hoodie with Cat Ears",
    section: "girls",
    category: "Tops",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.8,
    reviews: 280,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80",
    description: "Super soft warm fleece hoodie with cute hood detail and front pouch.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G213",
    name: "Classic Flat Slip-On Canvas Shoes",
    section: "girls",
    category: "Shoes",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.6,
    reviews: 195,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
    description: "Breathable elastic side canvas shoes for quick hostel walks and class.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G214",
    name: "Layered Butterfly Gold Pendant Necklace Set",
    section: "girls",
    category: "Accessories",
    price: 299,
    originalPrice: 699,
    discount: 57,
    rating: 4.8,
    reviews: 410,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    description: "Anti-tarnish 18K gold plated multi-chain butterfly pendant necklace.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G215",
    name: "Himalaya Purifying Neem Face Wash (200ml)",
    section: "girls",
    category: "Beauty",
    price: 185,
    originalPrice: 260,
    discount: 28,
    rating: 4.7,
    reviews: 910,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Herbal soap-free face wash preventing pimples & purifying campus acne skin.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G216",
    name: "Ribbed Knit Crop Tank Top (Pack of 2)",
    section: "girls",
    category: "Tops",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.6,
    reviews: 240,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80",
    description: "Stretchable cotton ribbed crop sleeveless tops in neutral white and black.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G217",
    name: "Pleated High-Waist A-Line Tennis Skirt",
    section: "girls",
    category: "Dresses",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 185,
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&q=80",
    description: "Classic pleated skirt with built-in safety shorts liner.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G218",
    name: "Ankle Strap Block Heel Sandals",
    section: "girls",
    category: "Shoes",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.8,
    reviews: 155,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=600&q=80",
    description: "2.5 inch comfortable sturdy block heel sandals for presentations & college events.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G219",
    name: "Waterproof Makeup Organizer Travel Pouch",
    section: "girls",
    category: "Bags",
    price: 349,
    originalPrice: 699,
    discount: 50,
    rating: 4.7,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "Multi-compartment fold-out cosmetic bag with hanging hook for hostel bathroom.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G220",
    name: "Pack of 6 Satin Silk Hair Scrunchies",
    section: "girls",
    category: "Accessories",
    price: 199,
    originalPrice: 499,
    discount: 60,
    rating: 4.9,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80",
    description: "Soft anti-crease silk scrunchies that prevent hair breakage and frizz.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G221",
    name: "Traditional Printed Cotton Straight Kurti",
    section: "girls",
    category: "Dresses",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.7,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80",
    description: "Breathable pure cotton ethnic kurti ideal for ethnic day and everyday campus wear.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G222",
    name: "Neutrogena Ultra Sheer SPF 50+ Sunscreen",
    section: "girls",
    category: "Beauty",
    price: 260,
    originalPrice: 350,
    discount: 25,
    rating: 4.8,
    reviews: 820,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Broad spectrum UVA/UVB lightweight non-greasy dry touch sunscreen protection.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G223",
    name: "Cat-Eye UV Protection Sunglasses",
    section: "girls",
    category: "Accessories",
    price: 499,
    originalPrice: 1199,
    discount: 58,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
    description: "Chic cat-eye frame sunglasses with tinted gradient lenses.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G224",
    name: "Crossbody PU Leather Sling Bag with Gold Chain",
    section: "girls",
    category: "Bags",
    price: 699,
    originalPrice: 1499,
    discount: 53,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80",
    description: "Compact stylish handbag with detachable strap for phone, keys & lip gloss.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G225",
    name: "Soft Cotton Yoga Pants with Pocket",
    section: "girls",
    category: "Jeans",
    price: 649,
    originalPrice: 1299,
    discount: 50,
    rating: 4.8,
    reviews: 270,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=600&q=80",
    description: "High-waist squat-proof stretch leggings for morning jog and hostel lounging.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G226",
    name: "Maybelline Colossal Volume Waterproof Mascara",
    section: "girls",
    category: "Beauty",
    price: 299,
    originalPrice: 450,
    discount: 33,
    rating: 4.7,
    reviews: 650,
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?auto=format&fit=crop&w=600&q=80",
    description: "Collagen infused formula giving 2x instant lash volume without clumping.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G227",
    name: "Chic Oversized Formal Blazer Jacket",
    section: "girls",
    category: "Tops",
    price: 1899,
    originalPrice: 3799,
    discount: 50,
    rating: 4.8,
    reviews: 130,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80",
    description: "Tailored smart casual blazer for college conferences & corporate presentations.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G228",
    name: "Set of 3 Hoop Earrings (Gold, Silver, Rose Gold)",
    section: "girls",
    category: "Accessories",
    price: 249,
    originalPrice: 599,
    discount: 58,
    rating: 4.7,
    reviews: 390,
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight hypoallergenic stainless steel medium size hoop earrings.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G229",
    name: "Fluffy Plush Hostel Room Bedroom Slippers",
    section: "girls",
    category: "Shoes",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.8,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=600&q=80",
    description: "Faux fur soft padded indoor bedroom slippers keeping feet warm.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G230",
    name: "100% Pure Organic Aloe Vera Gel (250ml)",
    section: "girls",
    category: "Beauty",
    price: 220,
    originalPrice: 350,
    discount: 37,
    rating: 4.8,
    reviews: 510,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Multi-purpose hydrating gel for skin moisturizer and hair conditioner.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G231",
    name: "Casual Printed A-Line Summer Sundress",
    section: "girls",
    category: "Dresses",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.7,
    reviews: 160,
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=600&q=80",
    description: "Soft breathable rayon sundress with adjustable spaghetti straps.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G232",
    name: "Casual Slip-On Canvas Espadrilles",
    section: "girls",
    category: "Shoes",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.6,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=600&q=80",
    description: "Jute sole flat canvas espadrilles for lightweight summer wear.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G233",
    name: "Aesthetic Transparent Acrylic Hair Claw Clips (Pack of 4)",
    section: "girls",
    category: "Accessories",
    price: 199,
    originalPrice: 499,
    discount: 60,
    rating: 4.8,
    reviews: 430,
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80",
    description: "Strong spring non-slip hair jaw clips for thick hair styling.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G234",
    name: "Minimalist Leather Strap Analog Watch",
    section: "girls",
    category: "Accessories",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.7,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=80",
    description: "Pastel nude leather strap watch with minimalist silver dial face.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G235",
    name: "Plum Green Tea Alcohol-Free Toner (200ml)",
    section: "girls",
    category: "Beauty",
    price: 310,
    originalPrice: 390,
    discount: 20,
    rating: 4.8,
    reviews: 390,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "Green tea extracts toner shrinking open pores & controlling oil secretion.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G236",
    name: "High-Waist Skinny Fit Black Jeans",
    section: "girls",
    category: "Jeans",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80",
    description: "Super stretchable dark black ankle length jeans.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G237",
    name: "Waterproof Laptop Shoulder Tote Bag",
    section: "girls",
    category: "Bags",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.8,
    reviews: 240,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
    description: "Padded 14-inch laptop section with zipper top for daily campus commutes.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G238",
    name: "Cute Teddy Bear Embroidered Sweatshirt",
    section: "girls",
    category: "Tops",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.9,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80",
    description: "Fleece lined pullover sweater with cute chest embroidery.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G239",
    name: "Minimalist Silver Stacking Rings (Pack of 5)",
    section: "girls",
    category: "Accessories",
    price: 199,
    originalPrice: 499,
    discount: 60,
    rating: 4.6,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    description: "Mix and match stainless steel delicate finger rings.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G240",
    name: "Lakme Absolute Gel Eyeliner & Kajal Pencil",
    section: "girls",
    category: "Beauty",
    price: 249,
    originalPrice: 399,
    discount: 37,
    rating: 4.7,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?auto=format&fit=crop&w=600&q=80",
    description: "24-hour smudge-proof deep black water resistant kajal.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G241",
    name: "Ribbed Bodycon Knee-Length Dress",
    section: "girls",
    category: "Dresses",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.7,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    description: "Soft stretch knit bodycon dress with side slit.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G242",
    name: "Pastel Pink Wireless Noise-Cancelling Earbuds",
    section: "girls",
    category: "Accessories",
    price: 1299,
    originalPrice: 2999,
    discount: 56,
    rating: 4.8,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80",
    description: "Touch sensors with 30-hour playback & environmental noise cancellation.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G243",
    name: "Denim Overall Jumpsuit Dungarees",
    section: "girls",
    category: "Dresses",
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.8,
    reviews: 110,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    description: "Classic blue denim overalls with adjustable shoulder straps.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G244",
    name: "Compact LED Handheld Makeup Mirror",
    section: "girls",
    category: "Beauty",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.7,
    reviews: 215,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
    description: "Rechargeable ring light mirror with 3 brightness modes for hostel room.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G245",
    name: "Ethnic Jhumka Earring Set (Pack of 3)",
    section: "girls",
    category: "Accessories",
    price: 299,
    originalPrice: 699,
    discount: 57,
    rating: 4.8,
    reviews: 350,
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=80",
    description: "Oxidized silver handcrafted traditional jhumka earrings for college fests.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G246",
    name: "Classic White Button Down Oversized Shirt",
    section: "girls",
    category: "Tops",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 260,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80",
    description: "Timeless crisp cotton shirt worn tucked or as an outer layer.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "G247",
    name: "Moisturizing Tinted Lip Balm (Berry & Peach)",
    section: "girls",
    category: "Beauty",
    price: 175,
    originalPrice: 250,
    discount: 30,
    rating: 4.6,
    reviews: 490,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80",
    description: "Shea butter & Vitamin E formula nourishing dry lips with natural tint.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "G248",
    name: "Comfortable Elastic Waist Jogger Pants",
    section: "girls",
    category: "Jeans",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 195,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-soft cotton sweatpants with drawstring waistband & pockets.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "G249",
    name: "Rose Quartz Face Roller & Gua Sha Massager Set",
    section: "girls",
    category: "Beauty",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 280,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    description: "100% natural crystal massage tool reducing puffiness & boosting skin glow.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "G250",
    name: "Canvas Floral Print High-Top Sneakers",
    section: "girls",
    category: "Shoes",
    price: 1099,
    originalPrice: 2199,
    discount: 50,
    rating: 4.8,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=600&q=80",
    description: "Charming botanical embroidery on durable canvas high-tops.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },

  // ==========================================
  // STUDENT ESSENTIALS SECTION (50 UNIQUE PRODUCTS: S301 - S350)
  // ==========================================
  {
    id: "S301",
    name: "Multi-Compartment Waterproof College Backpack",
    section: "student",
    category: "Backpacks",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.9,
    reviews: 680,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "32L capacity backpack with dedicated 15.6-inch laptop pocket, USB charging port, and rain cover.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S302",
    name: "Classmate Spiral Notebook A4 Size (Set of 6, 200 Pages)",
    section: "student",
    category: "Stationery",
    price: 499,
    originalPrice: 750,
    discount: 33,
    rating: 4.8,
    reviews: 940,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "High-grade 70 GSM unruled spiral notebooks with sturdy poly cover for lecture notes.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S303",
    name: "Touch Control Rechargeable LED Desk Lamp",
    section: "student",
    category: "Study Lamps",
    price: 649,
    originalPrice: 1299,
    discount: 50,
    rating: 4.8,
    reviews: 520,
    image: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=600&q=80",
    description: "Flexible neck LED lamp with 3 color light modes (Warm, White, Daylight) & pen holder.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S304",
    name: "Stainless Steel Vacuum Insulated Water Bottle (1 Litre)",
    section: "student",
    category: "Water Bottles",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.9,
    reviews: 430,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "Keeps water cold for 24 hours & hot for 12 hours. BPA-free leakproof double wall steel.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S305",
    name: "Active Noise Cancelling Over-Ear Wireless Headphones",
    section: "student",
    category: "Earphones",
    price: 1999,
    originalPrice: 4999,
    discount: 60,
    rating: 4.8,
    reviews: 610,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    description: "Deep bass 40mm drivers, ANC for library concentration & 50-hour ultra-long battery life.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S306",
    name: "Aluminum Ergonomic Ventilated Laptop Stand",
    section: "student",
    category: "Laptop Accessories",
    price: 699,
    originalPrice: 1499,
    discount: 53,
    rating: 4.8,
    reviews: 390,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80",
    description: "Foldable 6-level height adjustable stand improving neck posture during long coding sessions.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S307",
    name: "Casio Scientific Calculator FX-991EX Classwiz",
    section: "student",
    category: "College Essentials",
    price: 1395,
    originalPrice: 1595,
    discount: 13,
    rating: 4.9,
    reviews: 1250,
    image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=600&q=80",
    description: "552 functions non-programmable solar powered calculator mandatory for engineering exams.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S308",
    name: "Smooth Gel Pen Pack (10 Blue + 5 Black)",
    section: "student",
    category: "Stationery",
    price: 199,
    originalPrice: 350,
    discount: 43,
    rating: 4.7,
    reviews: 540,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Quick drying waterproof Japanese gel ink pens for exam writing.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S309",
    name: "Pastel Aesthetic Highlighters Pack of 6",
    section: "student",
    category: "Stationery",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.8,
    reviews: 480,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Soft non-bleed pastel shades for textbook highlighting.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S310",
    name: "Multi-Plug Extension Board with 3 USB Ports",
    section: "student",
    category: "College Essentials",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 730,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Surge protected 4 AC socket power strip with 2-meter long cord for hostel desk.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S311",
    name: "Wireless Silent Optical Mouse with USB Receiver",
    section: "student",
    category: "Laptop Accessories",
    price: 399,
    originalPrice: 899,
    discount: 56,
    rating: 4.7,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Quiet click 1600 DPI ergonomic mouse for silent library usage.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S312",
    name: "Anti-Theft Backpack with Combination Lock",
    section: "student",
    category: "Backpacks",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.8,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "Hidden zipper closures with cut-resistant fabric for crowded buses and trains.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S313",
    name: "Foldable Portable Wooden Study Bed Table",
    section: "student",
    category: "College Essentials",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    description: "Multipurpose lap desk with tablet slot and cup holder for hostel bed studying.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S314",
    name: "RGB Backlit Mechanical Gaming Keyboard",
    section: "student",
    category: "Laptop Accessories",
    price: 1599,
    originalPrice: 3199,
    discount: 50,
    rating: 4.8,
    reviews: 340,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    description: "Tactile blue switches keyboard for fast typing & gaming sessions.",
    isNew: false,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "S315",
    name: "Ceramic Coffee Mug with Lid & Spoon (450ml)",
    section: "student",
    category: "College Essentials",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.7,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    description: "Microwave safe insulated ceramic mug for late night study coffee & tea.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S316",
    name: "Pack of 12 Sticky Notes Cube + Page Flags",
    section: "student",
    category: "Stationery",
    price: 199,
    originalPrice: 399,
    discount: 50,
    rating: 4.6,
    reviews: 410,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Bright self-adhesive memo pads for textbook indexing and exam reminders.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S317",
    name: "Electric Instant Travel Kettle (0.5 Litre)",
    section: "student",
    category: "College Essentials",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.8,
    reviews: 580,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f6?auto=format&fit=crop&w=600&q=80",
    description: "Fast boiling stainless steel kettle for Maggi, tea & hot water in hostel room.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S318",
    name: "Magnetic Whiteboard with Marker & Eraser (A3 Size)",
    section: "student",
    category: "Stationery",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.7,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Framed wall-mountable notice board for timetable, formulas & daily goal tracking.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S319",
    name: "SanDisk Ultra 64GB USB 3.0 Pen Drive",
    section: "student",
    category: "Laptop Accessories",
    price: 429,
    originalPrice: 850,
    discount: 50,
    rating: 4.8,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1609592424074-984407b31274?auto=format&fit=crop&w=600&q=80",
    description: "Up to 130MB/s transfer speed flash drive for project presentations & software.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S320",
    name: "Noise-Isolating In-Ear Wired Earphones with Mic",
    section: "student",
    category: "Earphones",
    price: 349,
    originalPrice: 699,
    discount: 50,
    rating: 4.6,
    reviews: 740,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    description: "Tangle-free braided cable with clear inline mic for online lectures & calls.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S321",
    name: "Camlin Geometry Box Set with Precision Compass",
    section: "student",
    category: "Stationery",
    price: 130,
    originalPrice: 180,
    discount: 28,
    rating: 4.7,
    reviews: 620,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Complete mathematical drawing set for engineering drawing & math.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S322",
    name: "Waterproof Desk Mat Extended Mouse Pad (80x30cm)",
    section: "student",
    category: "Laptop Accessories",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 410,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Non-slip rubber base desk pad fitting keyboard, mouse & coffee cup.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "S323",
    name: "Motivator Glass Water Bottle with Time Marker (1L)",
    section: "student",
    category: "Water Bottles",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.7,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "Borosilicate eco bottle with silicone protective sleeve & hourly hydration markers.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S324",
    name: "Compact USB Mini Desk Fan for Hostel",
    section: "student",
    category: "College Essentials",
    price: 449,
    originalPrice: 899,
    discount: 50,
    rating: 4.6,
    reviews: 280,
    image: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=600&q=80",
    description: "3-speed ultra quiet USB powered fan for hot summer study hours.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S325",
    name: "Expandable Document Accordion Folder (13 Pockets)",
    section: "student",
    category: "Stationery",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.8,
    reviews: 390,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "A4 size plastic organizer folder with index tabs for certificates & assignment sheets.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S326",
    name: "10000mAh Ultra-Slim Fast Power Bank",
    section: "student",
    category: "Laptop Accessories",
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.8,
    reviews: 560,
    image: "https://images.unsplash.com/photo-1609592424074-984407b31274?auto=format&fit=crop&w=600&q=80",
    description: "Compact pocket-sized power bank charging phone 2.5 times on a single charge.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S327",
    name: "Aesthetic Canvas Roll-Up Pencil Pouch Case",
    section: "student",
    category: "Stationery",
    price: 199,
    originalPrice: 399,
    discount: 50,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Multi-slot storage pouch for pens, highlighters, scales and erasers.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S328",
    name: "Sports Shaker Bottle with Protein Storage Compartment",
    section: "student",
    category: "Water Bottles",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.7,
    reviews: 410,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "700ml leakproof shaker with stainless steel wire whisk ball for whey protein.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S329",
    name: "Full HD 1080p Web Camera with Built-in Mic",
    section: "student",
    category: "Laptop Accessories",
    price: 1199,
    originalPrice: 2399,
    discount: 50,
    rating: 4.6,
    reviews: 195,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
    description: "Auto focus wide-angle webcam for online classes, Zoom interviews & coding contests.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S330",
    name: "Noise Cancellation Foam Ear Plugs for Studying (Pack of 5)",
    section: "student",
    category: "College Essentials",
    price: 149,
    originalPrice: 299,
    discount: 50,
    rating: 4.8,
    reviews: 350,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    description: "32dB noise reduction soft memory foam earplugs blocking noisy hostel environments.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S331",
    name: "Classic Leatherette Executive A5 Notebook Journal",
    section: "student",
    category: "Stationery",
    price: 349,
    originalPrice: 699,
    discount: 50,
    rating: 4.8,
    reviews: 260,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Hardcover 80 GSM 200 pages ruled diary with ribbon bookmark & elastic closure.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S332",
    name: "Ergonomic Memory Foam Chair Seat Cushion",
    section: "student",
    category: "College Essentials",
    price: 799,
    originalPrice: 1599,
    discount: 50,
    rating: 4.8,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    description: "Orthopedic coccyx cushion for lower back pain relief during study desk hours.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "S333",
    name: "Wireless Presenter Remote Clicker with Red Laser Pointer",
    section: "student",
    category: "Laptop Accessories",
    price: 599,
    originalPrice: 1199,
    discount: 50,
    rating: 4.7,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=600&q=80",
    description: "Plug & play PowerPoint presentation slide changer clicker.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S334",
    name: "Set of 4 Desk Cable Organizer Clips",
    section: "student",
    category: "Laptop Accessories",
    price: 149,
    originalPrice: 299,
    discount: 50,
    rating: 4.6,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Adhesive silicone cable holder management clips for charger cords.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S335",
    name: "Heavy Duty Metal Mesh Book Stand Holder",
    section: "student",
    category: "Study Lamps",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.7,
    reviews: 195,
    image: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=600&q=80",
    description: "Adjustable reading rest holder for heavy engineering textbooks & iPads.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S336",
    name: "High Performance Thermal Coffee Travel Flask (500ml)",
    section: "student",
    category: "Water Bottles",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "Flip lid double wall hot coffee tumbler fitting car & backpack side pockets.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S337",
    name: "Smart Key Finder Bluetooth Tracker Tag",
    section: "student",
    category: "College Essentials",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.6,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80",
    description: "Anti-loss alarm device for keys, wallet, room key and college ID card.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S338",
    name: "Aesthetic Daily Undated Desk Planner Pad",
    section: "student",
    category: "Stationery",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.8,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "50 tear-off sheets with hourly schedule, task checklist & habit tracker.",
    isNew: true,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S339",
    name: "Portable Clip-on Book Light for Night Reading",
    section: "student",
    category: "Study Lamps",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.7,
    reviews: 340,
    image: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&w=600&q=80",
    description: "Soft amber eye care LED clamp light for reading without disturbing roomies.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S340",
    name: "Super Soft Fleece Blanket for Hostel Bed",
    section: "student",
    category: "College Essentials",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.8,
    reviews: 420,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
    description: "Single size lightweight cozy warm microfiber throw blanket.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S341",
    name: "Foldable Canvas Laundry Bag Organizer",
    section: "student",
    category: "College Essentials",
    price: 349,
    originalPrice: 699,
    discount: 50,
    rating: 4.7,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
    description: "Waterproof inner lining hamper with sturdy aluminium handles.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S342",
    name: "Aesthetic Ceramic Desk Pen Holder Stand",
    section: "student",
    category: "Stationery",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.7,
    reviews: 180,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Nordic marble texture pencil cup for organized study table.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "S343",
    name: "Multi-Functional 7-in-1 Electronics Cleaning Brush Kit",
    section: "student",
    category: "Laptop Accessories",
    price: 299,
    originalPrice: 599,
    discount: 50,
    rating: 4.8,
    reviews: 510,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Keyboard key puller, screen spray, airbud tip cleaner & microfiber cloth.",
    isNew: true,
    isTrending: true,
    isBestSeller: true,
    isDeal: false
  },
  {
    id: "S344",
    name: "Ultra-Lightweight Packable Raincoat Poncho",
    section: "student",
    category: "College Essentials",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.6,
    reviews: 230,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=600&q=80",
    description: "Reusable hooded waterproof rain cape fitting over college backpack.",
    isNew: false,
    isTrending: false,
    isBestSeller: false,
    isDeal: true
  },
  {
    id: "S345",
    name: "Automatic Electric Pencil Sharpener",
    section: "student",
    category: "Stationery",
    price: 349,
    originalPrice: 699,
    discount: 50,
    rating: 4.7,
    reviews: 140,
    image: "https://images.unsplash.com/photo-1585336261026-8f5786372969?auto=format&fit=crop&w=600&q=80",
    description: "Battery operated heavy duty sharpener for graphite & colored pencils.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S346",
    name: "Stainless Steel Cutlery Set with Travel Case",
    section: "student",
    category: "College Essentials",
    price: 249,
    originalPrice: 499,
    discount: 50,
    rating: 4.7,
    reviews: 290,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    description: "Spoon, fork, chopsticks & straw for clean canteen and mess dining.",
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S347",
    name: "Surge Protected 6-Way Power Strip Tower",
    section: "student",
    category: "College Essentials",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    rating: 4.8,
    reviews: 320,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Vertical space saving extension socket tower with 4 USB fast charging ports.",
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S348",
    name: "Waterproof Bluetooth Shower Speaker",
    section: "student",
    category: "Earphones",
    price: 699,
    originalPrice: 1399,
    discount: 50,
    rating: 4.7,
    reviews: 380,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    description: "IPX7 waterproof portable suction cup speaker for hostel bath & room tunes.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  },
  {
    id: "S349",
    name: "Aesthetic Pastel Desk Organizer Drawer Box",
    section: "student",
    category: "Stationery",
    price: 499,
    originalPrice: 999,
    discount: 50,
    rating: 4.8,
    reviews: 260,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "Stackable plastic mini storage drawers for desk clips, sticky notes & accessories.",
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    isDeal: false
  },
  {
    id: "S350",
    name: "Ergonomic Memory Foam Wrist Rest Pad Set",
    section: "student",
    category: "Laptop Accessories",
    price: 399,
    originalPrice: 799,
    discount: 50,
    rating: 4.8,
    reviews: 310,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Keyboard & mouse wrist support cushion preventing RSI & wrist fatigue.",
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    isDeal: true
  }
];
